### ISSUE TITLE
Quick question about functionality

### ISSUE THREAD

**Issue by hector-m** [xthan/polyvore#9]
Hi,
I am reading through your paper and looking at your code and I have a quick question. Would I be able to input my own set of images for an outfit for it to tell me if it matches? For example I could take pictures of my actual clothes and then input them to your program for a response. Is this feasible?

Thanks

**Comment by xthan** [comment]
You can extract the image features of your images and feed them into the network to check the compatibility score (see the extract_feature.sh and predict_compatibility.sh for details). However, since my model is trained on product images from Polyvore, I am not sure how it will work on real-life images. I think there is a very high probability that the domain shift is so large that the network cannot give satisfactory results.
